#!/bin/bash
args="-a= -s $EMACS_SOCKET"

[ "$(pidof emacs)" ] && args="$args -c"

if [ "$1" ]; then
    "$EMACSCLIENT" $args "$@"
else
    "$EMACSCLIENT" $args -ne '(mpeschke/goto-or-create-untitled-buffer)'
fi
