#!/bin/bash

TARGET_DIR=("$@")
[ "x$1" == "x" ] && TARGET_DIR=(".")

function confirmDeletion() {
    local confirm=""
    until [ "x$confirm" == 'xy' ] || [ "x$confirm" == 'xn' ]
    do
        read -ep "    Delete [y/n]: " confirm
        confirm=$(echo "$confirm" | tr [:upper:] [:lower:])
    done
    [ "x$confirm" == 'xy' ]
}

function deleteWithConfirmation() {
    for file in "${@}"
    do
        if rm "$file"; then
            echo "    OK: $file"
        else
            echo "    FAIL: $file"
        fi
    done
}

function find-files-to-delete () {
    local target="$1"
    echo "Files matching: $target"
    FILES=()
    while read -rd '' file
    do
        FILES+=("$file")
        echo "  $file"
    done < <(find "${TARGET_DIR[@]}" -depth -iname "$target" -print0)

    if [ "x${FILES[*]}" != "x" ]; then
        if confirmDeletion; then
            deleteWithConfirmation "${FILES[@]}"
        else
            echo "   Skipping"
        fi
    fi
}

find-files-to-delete '*~'
