#!/bin/bash

if [ "$EMACS_SOCKET" ]; then
    args=(-s "$EMACS_SOCKET")
else
    args=()
fi

if [ "$1" ]; then
	"$EMACSCLIENT" "${args[@]}" "$@"
else
        "$EMACSCLIENT" "${args[@]}" -ne '(mpeschke/goto-or-create-untitled-buffer)'
fi
